### PR TITLE
Changing to plexupdate script for installation

### PR DESCRIPTION
**Pull request by jhunthrop**
Since the debian repositories are no longer hosted, updating to use plexupdate.sh (credit to mrworf) to always get current debian package. Also allows the downloading of the plex pass version if desired.

### CODE REVIEW

**Comment by bhavicp** [comment]
>Since the debian repositories are no longer hosted,

What do you mean by that? The repo seems to be online and I don't see anything of it being taken offline?

I'm all for switching to the plexupdate.sh though, would be good not to rely on a user hosted repo (and the delays it has)

**Comment by jhunthrop** [comment]
Touche.. They must have been down yesterday when I was trying to rebuild my plex image. I was getting port 80 denies. I correlated that with some reddit posts that ninthgate was no longer hosting the repos and made a bad assumption.

**Comment by bhavicp** [comment]
FWIW - On the official thread @ Plex.tv (which the owner is responding on) the owner did say it was down and that he's going to be fixing it tomorrrow, was some Apache problem and it changing to port 8080.

At any rate, as I mentioned, would still be worth while!

**Comment by timhaak** [comment]
I like the idea. Though not sure how to then build an image for people with plexpass as going down this route would require that they build their own image setting the correct variables.

P.s with the pull request its set to use the plexpass version (Seems to be the default).

Also if we go down this route I'd rather use an environmental variable from the docker file than a hidden file in root. Only reason being that there is one file that has the settings. I see that the script accepts variables from the command line so could do it that way or alter the script to use environmental variables. 

I have been toying with building a simple gui image that can pull update and setup a system. This was mainly to get around the file rights problems. 

Though it should then also tie in nicely with this. Basically people could pull the prebuilt images or could have the gui build the images  locally and change things like this.

**Pull request closed without merging**
