### PR TITLE
Rockerfile instead of Dockerfile to generate both plex and plexpass images

### PR DESCRIPTION
**Pull request by kalbasit**
We currently have [timhaak/plex](https://hub.docker.com/r/timhaak/plex/) and [timhaak/plexpass](https://hub.docker.com/r/timhaak/plexpass/) generated from two different Github repositories making it harder for us to maintain Dockerfile and scripts. This PR allows us to use Travis-CI to build both images and push them directly to Docker hub all from one Rockerfile.

What is a Rockerfile? Rockerfile is the file used by [Rocker](https://github.com/grammarly/rocker) that adds a lot more functionality to building docker images. Used here: 1) [text/template](https://godoc.org/text/template) to do conditional and string interpolation 2) Tagging and pushing directly to Docker hub.

### CODE REVIEW

**Comment by kalbasit** [comment]
@timhaak This PR is missing one important information that, fortunately, I do not have :). Your Docker hub username and password. Here's what you can do to *encrypt* and add these to `.travis.yml`

```
travis encrypt DOCKER_USER=timhaak
```
and
```
travis encrypt DOCKER_PASS=supersecret
```

Each command gives you a `secure: ...` that you should add to `.travis.yml` and push to this branch. `.travis.yml` should look like this:


```
sudo: required
services:
  - docker
language: c
env:
  global:
    - ROCKER_VERSION=0.2.2
    # DOCKER_USER
    - secure: ...
    # DOCKER_PASS
    - secure: ...
before_script:
  - curl -L https://github.com/grammarly/rocker/releases/download/${ROCKER_VERSION}/rocker-${ROCKER_VERSION}_linux_amd64.tar.gz | sudo tar -C /usr/bin -xzf -
script:
  - if [[ "${TRAVIS_BRANCH}" = "master" ]]; then
      rocker build --var PLEXAPTLIST=wheezy --var PLEXMEDIASERVER_VERSION=`cat VERSION` --push --auth $DOCKER_USER:$DOCKER_PASS;
      rocker build --var PLEXAPTLIST=plexpass --var PLEXMEDIASERVER_VERSION=`cat VERSION_PASS` --push --auth $DOCKER_USER:$DOCKER_PASS;
    fi
```

**Comment by kalbasit** [comment]
Oh and also the docker images on Docker hub should not be an automated build any longer. Travis will be in charge of building the images itself.

**Comment by kalbasit** [comment]
Also if you can enable travis for this repo (conditional on `.travis.yml` existing). I'd be able to test this to make sure I've made no mistakes.

**Comment by timhaak** [comment]
Hi

I'm going to have to sit and think about this.

I currently peffer using native docker only as if someone want to build it that's all they need.

But let me go over this quiet over the weekend and will get back to you.

**Comment by timhaak** [comment]
Hi

Thanks for all the merging etc. 

I've thought quite a bit about this.

I would prefer to only use the native docker options more so that if people want to build there own they don't now have to learn something else.

I like the idea though and also like that there is a branch using this.

Part of the reason I trigger the build remotely is to also trigger builds on plex updates and not just on pushes.

I do like the idea of travis and we could possibly use travis with two separate dockerfiles to combine the versions. 

Though currently don't really have free time to look into this.

**Pull request closed without merging**
