### PR TITLE
Code cleanup. Resolves #46

### LINKED ISSUE #46: Inconsistent use of short-circuits and zero-length string checks in `start.sh`
There seems to be an inconsistent use of short circuits in the `start.sh` script:

- https://github.com/timhaak/docker-plex/blob/master/start.sh#L27
- https://github.com/timhaak/docker-plex/blob/master/start.sh#L42
- https://github.com/timhaak/docker-plex/blob/master/start.sh#L64

The three linked above are 3 different ways of doing a zero-length string check. Personally I am a fan of verbosity so would use the `-n` operator but am indifferent when it comes to the short circuit - for me that usually depends on if it's a one line or multiline block afterwards which is actually the opposite of how they have been used in this script.

Seeing as there seems to be more activity on this project now, might be nice to clean up the entrypoint script and get things consistent.

### PR DESCRIPTION
**Pull request by flungo**
Some code cleanup and restructuring.

- Fixes #46
- Extracts repeated code and constants to functions and variables respectively
- Some optimisation

### CODE REVIEW

**Comment by timhaak** [comment]
Hi

Sorry would you mind doing this one again. Some of the previous pull request now seem to have created merge conflicts.

I did the debug one but this one is a bit more complicated and would prefer if you could do the merge and check that its working as you originally intended. 

Thanks

**Comment by timhaak** [comment]
P.s feel free to merge it in yourself you should have the rights.

**Comment by flungo** [comment]
No worries, should be able to rebase and upload later this week. I do have permission to push to master and merge but I always like to get a second opinion before merging features I think are a good idea (as others might not agree) particularly since its not one of my own projects. Suppose it's habit from work where everything is code reviewed before it goes to the sacred master branch ;) (along with creating a separate branch for each feature, big or small).

**Comment by timhaak** [comment]
This should not be merged I think.

There were some conflicts that I think I fixed. 

Going to merge you next pull request.

If you could double check after that merge please.

**Pull request closed without merging**
